---
title: "Bioassay screen on 4 chmielewskii genotypes"
author: "Lissy Denkers"
date: "`r Sys.Date()`"
output: 
  pdf_document: default
  html_document: default
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.width = 8, 
                      fig.height = 5, 
                      fig.align = "center")
suppressPackageStartupMessages(library("ggplot2"))
suppressPackageStartupMessages(library("ggpubr"))
suppressPackageStartupMessages(library("ggpubfigs"))
suppressPackageStartupMessages(library("ggsignif"))
suppressPackageStartupMessages(library("patchwork"))
suppressPackageStartupMessages(library("multcomp"))
suppressPackageStartupMessages(library("car"))
suppressPackageStartupMessages(library("tidyverse"))
suppressPackageStartupMessages(library("rstatix"))
suppressPackageStartupMessages(library("broom"))
suppressPackageStartupMessages(library("DescTools"))
```

# Data import 

## Background information

This is the  the whitefly development bioassay on S. chmielewskii accesions LA1840, LA1028, LA1330 and LA2663 and S. lycopersicum cv MM. Only two counts were performed: the number of eggs and an end point nymph count (of all developmental stages).

## The raw data
```{r flies}
flies <- read.csv("raw_data.csv", 
                         header = T, 
                         sep = ",", 
                         dec = ".", 
                         check.names = FALSE) %>%    
  dplyr::filter(place != "13") %>%
  dplyr::filter(place != "21") %>%
  dplyr::filter(place != "22") %>%
  mutate_if(is.character, str_replace_all, 
            pattern = "0_egg", replacement = "egg") %>%
  mutate_if(is.character, str_replace_all, 
            pattern = "1_first_instar", replacement = "first_instar") %>%
  mutate_if(is.character, str_replace_all, 
            pattern = "2_second_instar", replacement = "second_instar") %>%
  mutate_if(is.character, str_replace_all, 
            pattern = "3_third_instar", replacement = "third_instar") %>%
  mutate_if(is.character, str_replace_all, 
            pattern = "4_fourth_instar", replacement = "fourth_instar") %>%
  mutate_if(is.character, str_replace_all, 
            pattern = "5_exuviea", replacement = "exuviea") %>%
  mutate_if(is.character, str_replace_all, 
            pattern = "MM", replacement = "cv") %>%
#  mutate(genotype = factor(genotype, levels = c("MB", "IL28", "IL27"))) %>%
  mutate(stage = factor(stage, levels = c("egg", "first_instar", "second_instar", "third_instar", "fourth_instar", "exuviea")))
# The first 10 rows of the data
knitr::kable(flies[1:10,1:7])
```

```{r wide}
flies <- flies %>%
  mutate(stage = as.factor(stage)) %>%
  pivot_wider(names_from = stage, values_from = number) 
```
 
```{r total fourth instars}
flies <- flies %>%
  dplyr::mutate(fourth_instar = fourth_instar + exuviea) %>%
  dplyr::select(-exuviea)
print(flies)
```

```{r}
flies <- flies %>%
  dplyr::group_by(place) %>%
  dplyr::mutate(egg = max(egg, na.rm = TRUE))%>%
  dplyr::mutate(first_instar = max(first_instar))%>%
  dplyr::mutate(second_instar = max(second_instar))%>%
  dplyr::mutate(third_instar = max(third_instar))%>%
  dplyr::mutate(fourth_instar = max(fourth_instar)) %>%
  dplyr::mutate(fourth_per_eggs = (max(fourth_instar)/max(egg))*100) %>%
  dplyr::ungroup() %>%
  dplyr::filter(day == 3) %>%
  mutate(genotype = factor(genotype, levels = c("cv", "LA1028", "LA1330", "LA1840", "LA2663"))) 
#  mutate(stage = factor(stage, levels = c("egg", "first_instar", #"second_instar", "third_instar", "fourth_instar", "exuviea")))
print(flies)
```



# Statistics

```{r glm eggs}
glm1 <- glm(formula = egg ~ genotype,
            family = poisson(),
            data = flies)

summary(glm1)
anova(glm1)
```

```{r anova eggs}
anova1 <- flies %>%
          anova_test(formula = egg ~ genotype)

anova1

```

```{r calculate median and SD eggs}
flies %>%
  group_by(genotype) %>%
  dplyr::summarise(mean = mean(egg), SD = sd(egg), 
            SE = sd(egg)/sqrt(n()))
```

```{r anova fourth}

anova2 <- flies %>%
          anova_test(formula = fourth_instar ~ genotype)

anova2

```

```{r calculate median and SD eggs}
flies %>%
  group_by(genotype) %>%
  dplyr::summarise(mean = mean(fourth_instar), SD = sd(fourth_instar), 
            SE = sd(fourth_instar)/sqrt(n()))
```

```{r anova percentage to fourth}

anova3 <- flies %>%
          anova_test(formula = fourth_per_eggs ~ genotype)

anova3
```

```{r dunnett}
  test1 <- DunnettTest(x=flies$egg, g=flies$genotype)
  test2 <- DunnettTest(x=flies$fourth_instar, g=flies$genotype)
  test3 <- DunnettTest(x=flies$fourth_per_eggs, g=flies$genotype)
  test1
  test2
  test3
```

```{r calculate median and SD % eggs to 4th}
flies %>%
  group_by(genotype) %>%
  dplyr::summarise(mean = mean(fourth_per_eggs), SD = sd(fourth_per_eggs), 
            SE = sd(fourth_per_eggs)/sqrt(n()))
```


# Plot

## palette for plots
```{r color palette}
palette <- c("#E69F00", "#bbe1f6", "#88caef", "#56B4E9", "#4490ba")
```

```{r check color palette}
library(colorblindcheck)
palette_check(palette, plot=TRUE)
```

## The actual plots
```{r combined plot, fig.width = 16, fig.height = 10}
p1 <- flies %>% 
  ggplot(aes(x=genotype, y=egg)) + 
  labs(y = "eggs (count)") +
  geom_boxplot(aes(fill = genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 0.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette)  +  
  scale_y_continuous(expand = c(0, 0), limits = c(0, 100))  +
  geom_signif(comparison = list(c("cv","LA1028"), c("cv", "LA1840")), 
              map_signif_level = TRUE, annotations = c("***", "***"),
              y_position = c(83, 90))


p3 <- flies %>% 
  ggplot(aes(x=genotype, y=fourth_per_eggs)) + 
  labs(y = "development to 4th instar (%)") +
  geom_boxplot(aes(fill=genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 0.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette)   +  
  scale_y_continuous(expand = c(0, 0), limits = c(0, 100))  +
  geom_signif(comparison = list(c("cv","LA1028"), c("cv", "LA1840")), 
              map_signif_level = TRUE, annotations = c("**", "*"),
              y_position = c(80, 90))

collected <- (p1 + p3) / guide_area() +
  plot_layout(guides = 'collect') +
  plot_annotation(tag_levels = 'a')

collected

ggsave(filename = "4_chmielewskii_bioassay.png", plot = collected, width = 10, height = 10)
ggsave(filename = "4_chmielewskii_bioassay.svg", plot = collected, width = 10, height = 10)
```
