---
title: "nymph plots"
author: "Lissy Denkers"
date: "`r Sys.Date()`"
output: 
  pdf_document: default
  html_document: default
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.width = 8, 
                      fig.height = 5, 
                      fig.align = "center")
suppressPackageStartupMessages(library("ggplot2"))
suppressPackageStartupMessages(library("ggrepel"))
suppressPackageStartupMessages(library("ggpubr"))
suppressPackageStartupMessages(library("ggpubfigs"))
suppressPackageStartupMessages(library("patchwork"))
suppressPackageStartupMessages(library("lemon"))
suppressPackageStartupMessages(library("plyr"))
suppressPackageStartupMessages(library("dplyr"))
suppressPackageStartupMessages(library("skimr"))
suppressPackageStartupMessages(library("Hmisc"))
suppressPackageStartupMessages(library("tidyr"))
suppressPackageStartupMessages(library("car"))
suppressPackageStartupMessages(library("rstatix"))
suppressPackageStartupMessages(library("tidyverse"))
suppressPackageStartupMessages(library("broom"))
suppressPackageStartupMessages(library("drc"))
suppressPackageStartupMessages(library("modelr"))
suppressPackageStartupMessages(library("egg"))
suppressPackageStartupMessages(library("tidydrc"))
suppressPackageStartupMessages(library("aomisc"))
suppressPackageStartupMessages(library("devtools"))
```

# data import

## The raw data
```{r flies}
flies <- read.csv("raw_data.csv", 
                         header = T, 
                         sep = ",", 
                         dec = ".", 
                         check.names = FALSE)
# The first 10 rows of the data
#knitr::kable(flies[1:10,1:8])
```


```{r filter}
flies <- flies %>%     
  dplyr::filter(place != 4) %>%     
  dplyr::filter(place < 13)
```

```{r wide}
flies <- flies %>%
  mutate(stage = as.factor(stage)) %>%
  pivot_wider(names_from = stage, values_from = number) 
```
 
```{r total fourth instars}
flies <- flies %>%
  mutate(fourth_exuviae = `5_late_fourth_instar` + `6_exuviea`) %>%
  group_by(place) %>%
  mutate(`5_completed_lifecycle` = cumsum(fourth_exuviae)) %>%
  mutate(`6_total_fourth_instars` = `4_early_fourth_instar` + `5_completed_lifecycle`) %>%
  ungroup()
```

```{r relative flies}
relative_flies <- flies %>%
  dplyr::select(-`4_early_fourth_instar`: -`5_completed_lifecycle`)

relative_flies <- relative_flies %>%
  mutate(first_instars = rowSums(relative_flies[,8:11])) %>%
  mutate(second_instars = rowSums(relative_flies[,9:11])) %>%
  mutate(third_instars = rowSums(relative_flies[,10:11])) %>%
  mutate(fourth_instars = `6_total_fourth_instars`)

relative_flies <- relative_flies %>%
  group_by(place) %>%
  mutate(first = `1_first_instar` / max(eggs_start))%>%
  mutate(second = `2_second_instar` / max(first_instars))%>%
  mutate(third = `3_third_instar` / max(second_instars))%>%
  mutate(fourth = fourth_instars / max(third_instars)) %>%
  ungroup()

relative_flies <- relative_flies %>%
  dplyr::select(-eggs_start: -fourth_instars)

relative_flies <- relative_flies %>%
  pivot_longer(cols = first:fourth, 
               names_to = "stage", values_to = "number") %>%
  mutate(genotype = factor(genotype, levels = c("MM", "LA1840"))) 
```

```{r test_flies}
test_flies <- relative_flies
# 10 rows of middle of the data
knitr::kable(test_flies[197:207,1:6])
```

## adjust data

```{r wide2}
test_flies <- test_flies %>%
  mutate(stage = as.factor(stage)) %>%
  mutate(place = as.factor(place)) %>%
  group_by(stage, genotype) %>%
  pivot_wider(names_from = place, values_from = number) 

# 10 rows of middle of the data
#knitr::kable(test_flies[41:51,1:15])
``` 

```{r median SD}
test_flies <- test_flies %>%
  mutate(day = as.factor(day)) %>%
  rowwise() %>%
  mutate(mean_number = mean(c_across(`1`:`12`), na.rm = TRUE)) %>%
  mutate(median_number = median(c_across(`1`:`12`), na.rm = TRUE)) %>%
  mutate(sd_number = sd(c_across(`1`:`12`), na.rm = TRUE)) %>%
  mutate(max_number = max(c_across(`1`:`12`), na.rm = TRUE)) %>%
  mutate(min_number = min(c_across(`1`:`12`), na.rm = TRUE))

test_flies <- test_flies %>%
  dplyr::select(-`1`: -`12`)

# 10 rows of middle of the data
knitr::kable(test_flies[41:51,1:9])
```

# graphs development relative to previous stage

Graphs with observed minima en maxima (dotted lines), confidence interval (median +/- SD; filled area) and median (solid line) per genotype per day for each stage, relative to the previous stage.

```{r palette}
palette <- c("#E69F00", "#56B4E9")
```

```{r first instars}

pfirst <- test_flies %>%
  dplyr::filter(stage == "first") %>% 
  mutate(day = as.numeric(as.character(day))) %>% 
  group_by(genotype) %>% 
  ggplot() +
  theme_simple() +
  labs(y = "first",
       x = "days after infection") +
  scale_color_manual(values = palette) +
  scale_fill_manual(values = palette) +
  geom_line(aes(x = day,
                  y = min_number,
                  color = genotype),
              linetype = "dotted") +
  geom_line(aes(x = day,
                  y = max_number,
                  color = genotype),
              linetype = "dotted") +
  geom_ribbon(aes(x = day,
                  ymin = (median_number - sd_number),
                  ymax = (median_number + sd_number),
                  fill = genotype),
              alpha = 0.35) +
  geom_line(aes(x = day,
                y = median_number,
                color = genotype),
            size = 1.2)

```

```{r second instars}
psecond <- test_flies %>%
  dplyr::filter(stage == "second") %>% 
  mutate(day = as.numeric(as.character(day))) %>% 
  group_by(genotype) %>% 
  ggplot() +
  theme_simple() +
  labs(y = "second",
       x = "days after infection") +
  scale_color_manual(values = palette) +
  scale_fill_manual(values = palette) +
  geom_line(aes(x = day,
                  y = min_number,
                  color = genotype),
              linetype = "dotted") +
  geom_line(aes(x = day,
                  y = max_number,
                  color = genotype),
              linetype = "dotted") +
  geom_ribbon(aes(x = day,
                  ymin = (median_number - sd_number),
                  ymax = (median_number + sd_number),
                  fill = genotype),
              alpha = 0.35) +
  geom_line(aes(x = day,
                y = median_number,
                color = genotype),
            size = 1.2)

```

```{r third instars}
pthird <- test_flies %>%
  dplyr::filter(stage == "third") %>% 
  mutate(day = as.numeric(as.character(day))) %>% 
  group_by(genotype) %>% 
  ggplot() +
  theme_simple() +
  labs(y = "Third",
       x = "days after infection") +
  scale_color_manual(values = palette) +
  scale_fill_manual(values = palette) +
  geom_line(aes(x = day,
                  y = min_number,
                  color = genotype),
              linetype = "dotted") +
  geom_line(aes(x = day,
                  y = max_number,
                  color = genotype),
              linetype = "dotted") +
  geom_ribbon(aes(x = day,
                  ymin = (median_number - sd_number),
                  ymax = (median_number + sd_number),
                  fill = genotype),
              alpha = 0.35) +
  geom_line(aes(x = day,
                y = median_number,
                color = genotype),
            size = 1.2) 

```

```{r fourth instars}
pfourth <- test_flies %>%
  dplyr::filter(stage == "fourth") %>% 
  mutate(day = as.numeric(as.character(day))) %>% 
  group_by(genotype) %>% 
  ggplot() +
  theme_simple() +
  labs(y = "fourth",
       x = "days after infection") +
  scale_color_manual(values = palette) +
  scale_fill_manual(values = palette) +
  geom_line(aes(x = day,
                  y = min_number,
                  color = genotype),
              linetype = "dotted") +
  geom_line(aes(x = day,
                  y = max_number,
                  color = genotype),
              linetype = "dotted") +
  geom_ribbon(aes(x = day,
                  ymin = (median_number - sd_number),
                  ymax = (median_number + sd_number),
                  fill = genotype),
              alpha = 0.35) +
  geom_line(aes(x = day,
                y = median_number,
                color = genotype),
            size = 1.2)

(pfirst + psecond) / (pthird + pfourth)  / guide_area() +
  plot_layout(guides = 'collect')
```



## cummulative numbers



```{r cumulative data}
relative_cummulative <- flies %>%
  dplyr::select(-`4_early_fourth_instar`: -`5_completed_lifecycle`)

relative_cummulative <- relative_cummulative %>%
  mutate(first_instars = rowSums(relative_cummulative[,8:11])) %>%
  mutate(second_instars = rowSums(relative_cummulative[,9:11])) %>%
  mutate(third_instars = rowSums(relative_cummulative[,10:11])) %>%
  mutate(fourth_instars = `6_total_fourth_instars`)

relative_cummulative <- relative_cummulative %>%
  group_by(place) %>%
  mutate(first = first_instars / max(first_instars))%>%
  mutate(second = second_instars / max(first_instars))%>%
  mutate(third = third_instars / max(first_instars))%>%
  mutate(fourth = fourth_instars / max(first_instars)) %>%
  ungroup()

relative_cummulative <- relative_cummulative %>%
  dplyr::select(-eggs_start: -fourth_instars)

relative_cummulative <- relative_cummulative %>%
  pivot_longer(cols = first:fourth, 
               names_to = "stage", values_to = "number") %>%
  mutate(genotype = factor(genotype, levels = c("MM", "LA1840"))) 

relative_cummulative <- relative_cummulative %>%
  mutate(stage = as.factor(stage)) %>%
  mutate(place = as.factor(place)) %>%
  group_by(stage, genotype) %>%
  pivot_wider(names_from = place, values_from = number)

relative_cummulative <- relative_cummulative %>%
  mutate(day = as.factor(day)) %>%
  rowwise() %>%
  mutate(median_abundance = median(c_across(`1`:`12`), na.rm = TRUE)) %>%
  mutate(max_abundance = max(c_across(`1`:`12`), na.rm = TRUE)) %>%
  mutate(min_abundance = min(c_across(`1`:`12`), na.rm = TRUE)) %>%
  mutate(sd_abundance = sd(c_across(`1`:`12`), na.rm = TRUE))


```

```{r functions}
cumul_median <- function(data) {
    for(i in 1:dim(data)[1]) {
    if(data$day[i] == 2) { data$median_new[i] <- data$median_new[i]  
    } else {
      if(data$median_new[i] < data$median_new[i-1]) {
    data$median_new[[i]] <- data$median_new[[i-1]] 
      } else {
    data$median_new[[i]] <- data$median_new[[i]]    
      } 
    }
    }   
    data$median_new
  } 
  
cumul_fun <- function(data) {
  rel_cumul = tibble()
 for(i in c("LA1840_first", "LA1840_second", "LA1840_third", "LA1840_fourth", "MM_first", "MM_second", "MM_third", "MM_fourth")){
   subdata = subset(data, id == i)
   subdata[[i]] = cumul_median(subdata)
   rel_cumul <- bind_rows(rel_cumul, subdata)
 }
  }
```


```{r correct}
relative_cumul <- relative_cummulative %>%
  mutate(median_new = median_abundance) %>%
  mutate(day = as.numeric(as.character(day))) %>%
  unite("id", c(genotype, stage), remove = FALSE)



relative_cumul1 <- cumul_fun(relative_cumul) %>%
  unite("median_abundance", LA1840_first:MM_fourth, 
                                  na.rm = TRUE)  %>%
  mutate(median_new = max_abundance)


relative_cumul2 <- cumul_fun(relative_cumul1) %>%
  unite("max_abundance", LA1840_first:MM_fourth, 
                                  na.rm = TRUE)  %>%
  mutate(median_new = min_abundance)


relative_cumul <- cumul_fun(relative_cumul2) %>%
  unite("min_abundance", LA1840_first:MM_fourth, 
                                  na.rm = TRUE)

```

```{r}
relative_cumul <- relative_cumul %>%
  mutate(day = as.factor(day)) %>% 
  mutate(median_abundance = as.numeric(as.character(median_abundance))) %>% 
  mutate(max_abundance = as.numeric(as.character(max_abundance))) %>% 
  mutate(min_abundance = as.numeric(as.character(min_abundance))) %>%
  rowwise() %>%
  mutate(ymin_ribbon = (median_abundance - sd_abundance)) %>%
  mutate(ymin_ribbon = if_else(ymin_ribbon < 0, 0, ymin_ribbon)) %>%
  mutate(day = as.numeric(as.character(day)))

relative_cummulative <- relative_cumul %>%
  dplyr::select(-`1`: -`12`) 
```

```{r relative cumulative graph, fig.width = 8, fig.height = 15}
p_cumulative <- relative_cummulative %>%
  mutate(stage = factor(stage, 
                        levels = c("first", "second", "third", "fourth"))) %>%
  mutate(day = as.numeric(as.character(day))) %>% 
  dplyr::filter(day > 6) %>% 
  group_by(genotype) %>% 
  ggplot() +
  theme_simple() +
  labs(y = "cumulative count (relative to hatched)",
       x = "days after infection") +
  scale_color_manual(values = palette) +
  scale_fill_manual(values = palette) +
  geom_line(aes(x = day,
                  y = min_abundance,
                  color = genotype),
              linetype = "dotted") +
  geom_line(aes(x = day,
                  y = max_abundance,
                  color = genotype),
              linetype = "dotted") +
  geom_ribbon(aes(x = day,
                  ymin = ymin_ribbon,
                  ymax = (median_abundance + sd_abundance),
                  fill = genotype),
              alpha = 0.35) +
  geom_line(aes(x = day,
                y = median_abundance,
                color = genotype),
            size = 1.2) +
  facet_rep_grid(vars(stage)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
  theme(panel.spacing = unit(0.1, "lines"))
```



## relative abundance

```{r new df}
relative_abundance <- flies %>%
  dplyr::select(-eggs_start: -`0_egg`,
                -`4_early_fourth_instar`:-`5_completed_lifecycle`)
```

```{r total abundance}
relative_abundance <- relative_abundance %>%
  rowwise() %>%
  mutate(total = sum(c_across(`1_first_instar`:`6_total_fourth_instars`),
                     na.rm = TRUE))
  
```

```{r relative abundances}
relative_abundance <- relative_abundance %>%
  mutate(first = `1_first_instar`/total) %>%
  mutate(second = `2_second_instar`/total) %>%
  mutate(third = `3_third_instar`/total) %>%
  mutate(fourth = `6_total_fourth_instars`/total)
```

```{r clean df}
relative_abundance <- relative_abundance %>%
  dplyr::select(-`1_first_instar`: -`6_total_fourth_instars`) %>%
  subset(total>0)
```

```{r longer}
relative_abundance <- relative_abundance %>%
  dplyr::select(-total) %>%
  pivot_longer(cols = first:fourth, 
               names_to = "stage", values_to = "relat_abund") %>%
  mutate(genotype = factor(genotype, levels = c("MM", "LA1840")))

# 10 rows of middle of the data
#knitr::kable(relative_abundance[41:51,1:6])
```

```{r wide3}
relative_abundance <- relative_abundance %>%
  mutate(stage = as.factor(stage)) %>%
  mutate(place = as.factor(place)) %>%
  group_by(stage, genotype) %>%
  pivot_wider(names_from = place, values_from = relat_abund) 

``` 

```{r summarised}
relative_abundance <- relative_abundance %>%
  mutate(day = as.factor(day)) %>%
  rowwise() %>%
  mutate(median_abundance = median(c_across(`1`:`12`), na.rm = TRUE)) %>%
  mutate(sd_abundance = sd(c_across(`1`:`12`), na.rm = TRUE)) %>%
  mutate(max_abundance = max(c_across(`1`:`12`), na.rm = TRUE)) %>%
  mutate(min_abundance = min(c_across(`1`:`12`), na.rm = TRUE)) %>%
  mutate(ymin_ribbon = (median_abundance - sd_abundance)) %>%
  mutate(ymin_ribbon = if_else(ymin_ribbon < 0, 0, ymin_ribbon))

relative_abundance <- relative_abundance %>%
  dplyr::select(-`1`: -`12`) 

# 10 rows of middle of the data
knitr::kable(relative_abundance[41:51,1:9])
```

```{r relative abundance on MM, eval=FALSE, include=FALSE}
MMpalette <- c("#E69F00")
#MMpalette <- c("#FF8900", "#FFB300", "#FFCD00", "#FFE280")
pMM <- relative_abundance %>%
  mutate(stage = factor(stage, 
                        levels = c("first", "second", "third", "fourth"))) %>%
  dplyr::filter(genotype == "MM") %>% 
  mutate(day = as.numeric(as.character(day))) %>% 
  group_by(stage) %>% 
  ggplot() +
  theme_simple() +
  labs(y = "relative abundance",
       x = "days after infection") +
  scale_color_manual(values = MMpalette) +
  scale_fill_manual(values = MMpalette) +
  geom_line(aes(x = day,
                  y = min_abundance,
                  color = genotype),
              linetype = "dotted") +
  geom_line(aes(x = day,
                  y = max_abundance,
                  color = genotype),
              linetype = "dotted") +
  geom_ribbon(aes(x = day,
                  ymin = ymin_ribbon,
                  ymax = (median_abundance + sd_abundance),
                  fill = genotype),
              alpha = 0.35) +
  geom_line(aes(x = day,
                y = median_abundance,
                color = genotype),
            size = 1.2) +
  facet_wrap(vars(stage), nrow = 4) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA))
```


```{r relative abundance graph, fig.width = 8, fig.height = 15}
#LApalette <- c("#0062F6", "#008DFF", "#2CB9FF", "#91E6FF")
p_abundance <- relative_abundance %>%
  mutate(stage = factor(stage, 
                        levels = c("first", "second", "third", "fourth"))) %>%
  #dplyr::filter(genotype == "LA1840") %>% 
  mutate(day = as.numeric(as.character(day))) %>% 
  group_by(genotype) %>% 
  ggplot() +
  theme_simple() +
  labs(y = "relative abundance per plant",
       x = "days after infection") +
  scale_color_manual(values = palette) +
  scale_fill_manual(values = palette) +
  geom_line(aes(x = day,
                  y = min_abundance,
                  color = genotype),
              linetype = "dotted") +
  geom_line(aes(x = day,
                  y = max_abundance,
                  color = genotype),
              linetype = "dotted") +
  geom_ribbon(aes(x = day,
                  ymin = ymin_ribbon,
                  ymax = (median_abundance + sd_abundance),
                  fill = genotype),
              alpha = 0.35) +
  geom_line(aes(x = day,
                y = median_abundance,
                color = genotype),
            size = 1.2) +
  facet_rep_grid(vars(stage)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
  theme(panel.spacing = unit(0.1, "lines"))


(p_abundance + p_cumulative) / guide_area() +
  plot_layout(guides = 'collect', 
              heights = unit(c(15, 15), 'cm'))
```
```

