---
title: "nymph plots"
author: "Lissy Denkers"
date: "`r Sys.Date()`"
output: 
  pdf_document: default
  html_document: default
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.width = 8, 
                      fig.height = 5, 
                      fig.align = "center")
suppressPackageStartupMessages(library("ggplot2"))
suppressPackageStartupMessages(library("ggrepel"))
suppressPackageStartupMessages(library("ggpubr"))
suppressPackageStartupMessages(library("ggpubfigs"))
suppressPackageStartupMessages(library("patchwork"))
suppressPackageStartupMessages(library("lemon"))
suppressPackageStartupMessages(library("plyr"))
suppressPackageStartupMessages(library("dplyr"))
suppressPackageStartupMessages(library("skimr"))
suppressPackageStartupMessages(library("Hmisc"))
suppressPackageStartupMessages(library("tidyr"))
suppressPackageStartupMessages(library("car"))
suppressPackageStartupMessages(library("rstatix"))
suppressPackageStartupMessages(library("tidyverse"))
suppressPackageStartupMessages(library("broom"))
suppressPackageStartupMessages(library("drc"))
suppressPackageStartupMessages(library("modelr"))
suppressPackageStartupMessages(library("egg"))
suppressPackageStartupMessages(library("tidydrc"))
suppressPackageStartupMessages(library("aomisc"))
suppressPackageStartupMessages(library("devtools"))
suppressPackageStartupMessages(library("svglite"))
```

# data import

## The raw data
```{r flies}
flies <- read.csv("raw_data.csv", 
                         header = T, 
                         sep = ",", 
                         dec = ".", 
                         check.names = FALSE)
# The first 10 rows of the data
#knitr::kable(flies[1:10,1:8])
```


```{r filter}
flies <- flies %>%     
  dplyr::filter(place != 4) %>%     
  dplyr::filter(place < 13)
```

```{r wide}
flies <- flies %>%
  mutate(stage = as.factor(stage)) %>%
  pivot_wider(names_from = stage, values_from = number) 
```
 
```{r total fourth instars}
flies <- flies %>%
  dplyr::mutate(fourth_exuviae = `5_late_fourth_instar` + `6_exuviea`) %>%
  dplyr::group_by(place) %>%
  dplyr::mutate(`5_completed_lifecycle` = cumsum(fourth_exuviae)) %>%
  dplyr::mutate(`6_total_fourth_instars` = `4_early_fourth_instar` + `5_completed_lifecycle`) %>%
  dplyr::ungroup()
```

```{r relative flies}
relative_flies <- flies %>%
  dplyr::select(-`4_early_fourth_instar`: -`5_completed_lifecycle`)

relative_flies <- relative_flies %>%
  mutate(first_instars = rowSums(relative_flies[,8:11])) %>%
  mutate(second_instars = rowSums(relative_flies[,9:11])) %>%
  mutate(third_instars = rowSums(relative_flies[,10:11])) %>%
  mutate(fourth_instars = `6_total_fourth_instars`)

relative_flies <- relative_flies %>%
  group_by(place) %>%
  mutate(first = `1_first_instar` / max(eggs_start))%>%
  mutate(second = `2_second_instar` / max(first_instars))%>%
  mutate(third = `3_third_instar` / max(second_instars))%>%
  mutate(fourth = fourth_instars / max(third_instars)) %>%
  ungroup()

relative_flies <- relative_flies %>%
  dplyr::select(-eggs_start: -fourth_instars)

relative_flies <- relative_flies %>%
  pivot_longer(cols = first:fourth, 
               names_to = "stage", values_to = "number") %>%
  mutate(genotype = factor(genotype, levels = c("MM", "LA1840"))) 
```

```{r test_flies}
test_flies <- relative_flies
# 10 rows of middle of the data
knitr::kable(test_flies[197:207,1:6])
```

## adjust data

```{r wide2}
test_flies <- test_flies %>%
  mutate(stage = as.factor(stage)) %>%
  mutate(place = as.factor(place)) %>%
  group_by(stage, genotype) %>%
  pivot_wider(names_from = place, values_from = number) 

# 10 rows of middle of the data
#knitr::kable(test_flies[41:51,1:15])
``` 

```{r median SD}
test_flies <- test_flies %>%
  mutate(day = as.factor(day)) %>%
  rowwise() %>%
  mutate(mean_number = mean(c_across(`1`:`12`), na.rm = TRUE)) %>%
  mutate(median_number = median(c_across(`1`:`12`), na.rm = TRUE)) %>%
  mutate(sd_number = sd(c_across(`1`:`12`), na.rm = TRUE)) %>%
  mutate(max_number = max(c_across(`1`:`12`), na.rm = TRUE)) %>%
  mutate(min_number = min(c_across(`1`:`12`), na.rm = TRUE))

test_flies <- test_flies %>%
  dplyr::select(-`1`: -`12`)

# 10 rows of middle of the data
knitr::kable(test_flies[41:51,1:9])
```

# graphs development relative to previous stage

Graphs with observed minima en maxima (dotted lines), confidence interval (median +/- SD; filled area) and median (solid line) per genotype per day for each stage, relative to the previous stage.

```{r palette}
palette <- c("#E69F00", "#56B4E9")
LApalette <- c("#aad9f4", "#56B4E9", "#2b5a74")
MMpalette <- c("#f2cf7f", "#E69F00", "#734f00")
```

```{r first instars}

pfirst <- test_flies %>%
  dplyr::filter(stage == "first") %>% 
  mutate(day = as.numeric(as.character(day))) %>% 
  group_by(genotype) %>% 
  ggplot() +
  theme_simple() +
  labs(y = "first",
       x = "days after infection") +
  scale_color_manual(values = palette) +
  scale_fill_manual(values = palette) +
  geom_line(aes(x = day,
                  y = min_number,
                  color = genotype),
              linetype = "dotted") +
  geom_line(aes(x = day,
                  y = max_number,
                  color = genotype),
              linetype = "dotted") +
  geom_ribbon(aes(x = day,
                  ymin = (median_number - sd_number),
                  ymax = (median_number + sd_number),
                  fill = genotype),
              alpha = 0.35) +
  geom_line(aes(x = day,
                y = median_number,
                color = genotype),
            size = 1.2)

```

```{r second instars}
psecond <- test_flies %>%
  dplyr::filter(stage == "second") %>% 
  mutate(day = as.numeric(as.character(day))) %>% 
  group_by(genotype) %>% 
  ggplot() +
  theme_simple() +
  labs(y = "second",
       x = "days after infection") +
  scale_color_manual(values = palette) +
  scale_fill_manual(values = palette) +
  geom_line(aes(x = day,
                  y = min_number,
                  color = genotype),
              linetype = "dotted") +
  geom_line(aes(x = day,
                  y = max_number,
                  color = genotype),
              linetype = "dotted") +
  geom_ribbon(aes(x = day,
                  ymin = (median_number - sd_number),
                  ymax = (median_number + sd_number),
                  fill = genotype),
              alpha = 0.35) +
  geom_line(aes(x = day,
                y = median_number,
                color = genotype),
            size = 1.2)

```

```{r third instars}
pthird <- test_flies %>%
  dplyr::filter(stage == "third") %>% 
  mutate(day = as.numeric(as.character(day))) %>% 
  group_by(genotype) %>% 
  ggplot() +
  theme_simple() +
  labs(y = "Third",
       x = "days after infection") +
  scale_color_manual(values = palette) +
  scale_fill_manual(values = palette) +
  geom_line(aes(x = day,
                  y = min_number,
                  color = genotype),
              linetype = "dotted") +
  geom_line(aes(x = day,
                  y = max_number,
                  color = genotype),
              linetype = "dotted") +
  geom_ribbon(aes(x = day,
                  ymin = (median_number - sd_number),
                  ymax = (median_number + sd_number),
                  fill = genotype),
              alpha = 0.35) +
  geom_line(aes(x = day,
                y = median_number,
                color = genotype),
            size = 1.2) 

```

```{r fourth instars}
pfourth <- test_flies %>%
  dplyr::filter(stage == "fourth") %>% 
  mutate(day = as.numeric(as.character(day))) %>% 
  group_by(genotype) %>% 
  ggplot() +
  theme_simple() +
  labs(y = "fourth",
       x = "days after infection") +
  scale_color_manual(values = palette) +
  scale_fill_manual(values = palette) +
  geom_line(aes(x = day,
                  y = min_number,
                  color = genotype),
              linetype = "dotted") +
  geom_line(aes(x = day,
                  y = max_number,
                  color = genotype),
              linetype = "dotted") +
  geom_ribbon(aes(x = day,
                  ymin = (median_number - sd_number),
                  ymax = (median_number + sd_number),
                  fill = genotype),
              alpha = 0.35) +
  geom_line(aes(x = day,
                y = median_number,
                color = genotype),
            size = 1.2)

(pfirst + psecond) / (pthird + pfourth)  / guide_area() +
  plot_layout(guides = 'collect')
```



## cummulative numbers

```{r functions}
cumul_median <- function(data) {
    for(i in 1:dim(data)[1]) {
    if(data$day[i] == 2) { data$var_new[i] <- data$var_new[i]  
    } else {
      if(data$var_new[i] < data$var_new[i-1]) {
    data$var_new[i] <- data$var_new[i-1] 
      } else {
    data$var_new[i] <- data$var_new[i]    
      } 
    }
    }   
    data$var_new
  } 
  
cumul_fun <- function(data) {
  rel_cumul = tibble()
 for(i in c("LA1840_1", "MM_2", "MM_3", "LA1840_5", "LA1840_6", "LA1840_7", "MM_8", "MM_9", "MM_10", "LA1840_11", "LA1840_12")){
   subdata = subset(data, id == i)
   subdata[[i]] = cumul_median(subdata)
   rel_cumul <- bind_rows(rel_cumul, subdata)
 }
  }
  
```

```{r cumulative data}
relative_cummulative <- flies %>%
  dplyr::select(-`4_early_fourth_instar`: -`5_completed_lifecycle`)

relative_cummulative <- relative_cummulative %>%
  dplyr::mutate(first_instars = rowSums(relative_cummulative[,8:11])) %>%
  dplyr::mutate(second_instars = rowSums(relative_cummulative[,9:11])) %>%
  dplyr::mutate(third_instars = rowSums(relative_cummulative[,10:11])) %>%
  dplyr::mutate(fourth_instars = `6_total_fourth_instars`)
```


```{r correct}
relative_cummulative <- relative_cummulative %>%
  dplyr::mutate(var_new = first_instars) %>%
  dplyr::mutate(day = as.numeric(as.character(day))) %>%
  unite("id", c(genotype, place), remove = FALSE) %>%
  dplyr::mutate(id = as.factor(id)) %>%
  dplyr::group_by(id)


  rel_cumul = tibble()
 for(i in c("LA1840_1", "MM_2", "MM_3", "LA1840_5", "LA1840_6", "LA1840_7", "MM_8", "MM_9", "MM_10", "LA1840_11", "LA1840_12")){
   subdata = subset(relative_cummulative, id == i)
   subdata[i] = cumul_median(subdata)
   rel_cumul <- bind_rows(rel_cumul, subdata)
 }


relative_cummulative <- rel_cumul %>%
  unite("first_instars", LA1840_1:LA1840_12, 
                                  na.rm = TRUE)  %>%
  dplyr::mutate(var_new = second_instars)

  rel_cumul = tibble()
 for(i in c("LA1840_1", "MM_2", "MM_3", "LA1840_5", "LA1840_6", "LA1840_7", "MM_8", "MM_9", "MM_10", "LA1840_11", "LA1840_12")){
   subdata = subset(relative_cummulative, id == i)
   subdata[i] = cumul_median(subdata)
   rel_cumul <- bind_rows(rel_cumul, subdata)
 }


relative_cummulative <- rel_cumul %>%
  unite("second_instars", LA1840_1:LA1840_12, 
                                  na.rm = TRUE)  %>%
  dplyr::mutate(var_new = third_instars)



  rel_cumul = tibble()
 for(i in c("LA1840_1", "MM_2", "MM_3", "LA1840_5", "LA1840_6", "LA1840_7", "MM_8", "MM_9", "MM_10", "LA1840_11", "LA1840_12")){
   subdata = subset(relative_cummulative, id == i)
   subdata[i] = cumul_median(subdata)
   rel_cumul <- bind_rows(rel_cumul, subdata)
 }


relative_cummulative <- rel_cumul %>%
  unite("third_instars", LA1840_1:LA1840_12, 
                                  na.rm = TRUE)  %>%
  dplyr::mutate(var_new = fourth_instars)



  rel_cumul = tibble()
 for(i in c("LA1840_1", "MM_2", "MM_3", "LA1840_5", "LA1840_6", "LA1840_7", "MM_8", "MM_9", "MM_10", "LA1840_11", "LA1840_12")){
   subdata = subset(relative_cummulative, id == i)
   subdata[i] = cumul_median(subdata)
   rel_cumul <- bind_rows(rel_cumul, subdata)
 }


relative_cummulative <- rel_cumul %>%
  unite("fourth_instars", LA1840_1:LA1840_12, 
                                  na.rm = TRUE)
```


```{r}
relative_cummulative <- relative_cummulative %>%
  dplyr::mutate(day = as.factor(day)) %>% 
  dplyr::mutate(first_instars = as.numeric(as.character(first_instars))) %>% 
  dplyr::mutate(second_instars = as.numeric(as.character(second_instars))) %>% 
  dplyr::mutate(third_instars = as.numeric(as.character(third_instars))) %>% 
  dplyr::mutate(fourth_instars = as.numeric(as.character(fourth_instars))) 


relative_cummulative <- relative_cummulative %>%
  dplyr::select(-`hatched`: -`6_total_fourth_instars`) 
```

```{r}
relative_cummulative <- relative_cummulative %>%
  dplyr::group_by(place) %>%
  dplyr::mutate(first = (first_instars / eggs_start)*100)%>%
  dplyr::mutate(second = (second_instars / max(first_instars))*100)%>%
  dplyr::mutate(third = (third_instars / max(first_instars))*100)%>%
  dplyr::mutate(fourth = (fourth_instars / max(first_instars))*100) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(genotype = factor(genotype, levels = c("MM", "LA1840")))

relative_cummulative <- relative_cummulative %>%
  dplyr::select(-var_new)

relative_cummulative <- relative_cummulative %>%
  pivot_longer(cols = eggs_start:fourth, 
               names_to = "stage", values_to = "number") %>%
  mutate(genotype = factor(genotype, levels = c("MM", "LA1840")))  %>%
  mutate(stage = factor(stage, levels = c("eggs_start", "first_instars", "second_instars", "third_instars", "fourth_instars", 
                                          "first", "second", "third", "fourth"))) 

auc <- relative_cummulative
ED <- relative_cummulative
```

```{r combined plot, fig.width = 16, fig.height = 10}

#egg and hatching
p_eggs <- relative_cummulative %>% 
  dplyr::filter(day == 29) %>%
  dplyr::filter(stage == "eggs_start") %>%
  ggplot(aes(x=genotype, y=number, fill=genotype)) + 
  labs(y = "eggs (count)") +
  geom_boxplot() +    
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 0.4)) +  
  scale_y_continuous(expand = c(0, 0), limits = c(0, 90)) +
  theme_simple() + 
  scale_fill_manual(values = palette)  +
  stat_compare_means(method = "t.test", 
                     label.y = 85,
                     label.x = 1.5,
                     size = 5,
                     label = "p.format")

p_first <- relative_cummulative %>% 
  dplyr::filter(day == 29) %>%
  dplyr::filter(stage == "first_instars") %>%
  ggplot(aes(x=genotype, y=number, fill=genotype)) + 
  labs(y = "hatched eggs (count)") +
  geom_boxplot() +    
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 0.4)) +  
  scale_y_continuous(expand = c(0, 0), limits = c(0, 90)) +
  theme_simple() + 
  scale_fill_manual(values = palette)  +
  stat_compare_means(method = "t.test", 
                     label.y = 85,
                     label.x = 1.5,
                     size = 5,
                     label = "p.format")

p1 <- relative_cummulative %>% 
  dplyr::filter(day == 29) %>%
  dplyr::filter(stage == "first") %>%
  ggplot(aes(x=genotype, y=number, fill=genotype)) + 
  labs(y = "hatched eggs (%)") +
  geom_boxplot() +     
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 0.4)) +  
  scale_y_continuous(expand = c(0, 0), limits = c(0, 100)) +
  theme_simple() + 
  scale_fill_manual(values = palette)  +
  stat_compare_means(method = "t.test", 
                     label.y = 95,
                     label.x = 1.5,
                     size = 5,
                     label = "p.format")

#nymph counts
p_MM <- relative_cummulative %>% 
  dplyr::filter(day == 29) %>%
  dplyr::filter(genotype == "MM") %>%
  dplyr::filter(stage == "second_instars" | stage == "third_instars" | stage == "fourth_instars") %>%
  ggplot(aes(x=stage, y=number, fill=stage)) + 
  labs(y = "nymphs (count)") +
  geom_boxplot() + 
  ylim(0,90) +
  theme_simple() + 
  scale_fill_manual(values = MMpalette) 

p_LA1840 <-  relative_cummulative %>% 
  dplyr::filter(day == 29) %>%
  dplyr::filter(genotype == "LA1840") %>%
  dplyr::filter(stage == "second_instars" | stage == "third_instars" | stage == "fourth_instars") %>%
  ggplot(aes(x=stage, y=number, fill=stage)) + 
  labs(y = "nymphs (count)") +
  geom_boxplot() + 
  ylim(0,90) +
  theme_simple() + 
  scale_fill_manual(values = LApalette) 

# development %
p_M <- relative_cummulative %>% 
  dplyr::filter(day == 29) %>%
  dplyr::filter(genotype == "MM") %>%
  dplyr::filter(stage == "second" | stage == "third" | stage == "fourth") %>%
  ggplot(aes(x=stage, y=number, fill=stage)) + 
  labs(y = "development to nymph stage (%)") +
  geom_boxplot() + 
  ylim(80,100) +
  theme_simple() + 
  scale_fill_manual(values = MMpalette) 

p_L <-  relative_cummulative %>% 
  dplyr::filter(day == 29) %>%
  dplyr::filter(genotype == "LA1840") %>%
  dplyr::filter(stage == "second" | stage == "third" | stage == "fourth") %>%
  ggplot(aes(x=stage, y=number, fill=stage)) + 
  labs(y = "development to nymph stage (%)") +
  geom_boxplot() + 
  ylim(80,100) +
  theme_simple() + 
  scale_fill_manual(values = LApalette) 


collected <- ((p_eggs | p_first | p1) / (p_MM| p_LA1840) / (p_M | p_L)) / guide_area() +
  plot_layout(guides = 'collect') +
  plot_annotation(tag_levels = 'a')

collected

#ggsave(filename = "graft_bioassay_boxplots.png", plot = collected, width = 10, height = 15)
```

```{r}
relative_cummulative <- relative_cummulative %>%
  dplyr::filter(stage == "first" | stage == "second" | stage == "third" | stage == "fourth")

relative_cummulative <- relative_cummulative %>%
  dplyr::mutate(genotype = factor(genotype, levels = c("MM", "LA1840"))) 

relative_cummulative <- relative_cummulative %>%
  dplyr::select(-id) %>%
  dplyr::mutate(stage = as.factor(stage)) %>%
  dplyr::mutate(place = as.factor(place)) %>%
  dplyr::group_by(stage, genotype) %>%
  pivot_wider(names_from = place, values_from = number)

relative_cummulative <- relative_cummulative %>%
  dplyr::mutate(day = as.factor(day)) %>%
  rowwise() %>%
  dplyr::mutate(median_abundance = median(c_across(`1`:`12`), na.rm = TRUE)) %>%
  dplyr::mutate(max_abundance = max(c_across(`1`:`12`), na.rm = TRUE)) %>%
  dplyr::mutate(min_abundance = min(c_across(`1`:`12`), na.rm = TRUE)) %>%
  #mutate(n = list(rowSums(na.omit(c(`1`:`12`)))))
  dplyr::mutate(IQR_abundance = IQR(c_across(`1`:`12`), na.rm = TRUE)) %>%
  dplyr::mutate(day = as.numeric(as.character(day))) %>%
  dplyr::select(-`1`: -`12`) 

relative_cummulative <- relative_cummulative %>%
  dplyr::mutate(ymin_ribbon = (median_abundance - (0.5*IQR_abundance))) %>%
  dplyr::mutate(ymin_ribbon = if_else(ymin_ribbon < 0, 0, ymin_ribbon)) %>% 
  dplyr::mutate(ymin_ribbon = if_else(min_abundance < ymin_ribbon, 
                                 ymin_ribbon, min_abundance)) %>%
  dplyr::mutate(min_whisker = (ymin_ribbon - (1.5*IQR_abundance))) %>%
  dplyr::mutate(min_whisker = if_else(min_abundance < min_whisker, 
                                 min_whisker, min_abundance)) %>%
  dplyr::mutate(min_whisker = if_else(min_whisker < 0, 0, min_whisker)) %>%
  dplyr::mutate(ymax_ribbon = (median_abundance + (0.5*IQR_abundance))) %>%
  dplyr::mutate(ymax_ribbon = if_else(max_abundance > ymax_ribbon, 
                                 ymax_ribbon, max_abundance)) %>%
  dplyr::mutate(max_whisker = (ymax_ribbon + (1.5*IQR_abundance))) %>%
  dplyr::mutate(max_whisker = if_else(max_abundance > max_whisker, 
                                 max_whisker, max_abundance))
```


## ED

```{r ED data}
library(lmtest)
library(sandwich)

ED <- ED %>%
  dplyr::filter(stage == "fourth")

ED <- ED  %>%
  dplyr::mutate(day = as.numeric(as.character(day)))

ED_MM <- ED %>%
  dplyr::filter(genotype  == "MM")

ED_LA <- ED %>%
  dplyr::filter(genotype  == "LA1840")

```

```{r calculate EmT50}
model_MM <- drm(number ~ day,
                data = ED_MM, 
                fct = LL.3(names = c("Slope", 
                                     "Upper Limit", 
                                     "ED50")))

coeftest(model_MM)

MM_ED <- ED(model_MM,
            c(10, 25, 50, 75),
            interval = "delta",
            type = "absolute")


model_LA <- drm(number ~ day,
                data = ED_LA, 
                fct = LL.3(names = c("Slope", 
                                     "Upper Limit", 
                                     "ED50")))
coeftest(model_LA)

LA_ED <- ED(model_LA,
            c(10, 25, 50, 75),
            interval = "delta",
            type = "absolute")
```
```{r}
ed_values <- tibble::tribble(
  ~genotype, ~ed,   ~stat,   ~value,
    "MM",   "EmT10", "mean (±SE)",  "16.81 (±0.26)",
    "MM",   "EmT25", "mean (±SE)",  "18.60 (±0.18)",
    "MM",   "EmT50", "mean (±SE)",  "20.67 (±0.21)",
    "MM",   "EmT75", "mean (±SE)",  "23.33 (±0.40)",
    "LA1840",   "EmT10", "mean (±SE)",  "18.10 (±0.23)",
    "LA1840",   "EmT25", "mean (±SE)",  "19.67 (±0.15)",
    "LA1840",   "EmT50", "mean (±SE)",  "21.54 (±0.20)",
    "LA1840",   "EmT75", "mean (±SE)",  "24.45 (±0.47)"
  )
```

```{r}
suppressPackageStartupMessages(library("gapminder"))
suppressPackageStartupMessages(library("dplyr"))
suppressPackageStartupMessages(library("tidyr"))
suppressPackageStartupMessages(library("stringr"))
suppressPackageStartupMessages(library("purrr"))
suppressPackageStartupMessages(library("gt"))
suppressPackageStartupMessages(library("mmtable2"))
suppressPackageStartupMessages(library("webshot"))
#webshot::install_phantomjs()
```

```{r EmT table}
ed_table <- ed_values %>%
  dplyr::mutate(genotype = factor(genotype, 
                                  levels = c("MM", "LA1840"))) %>%
  mmtable(cells = value) +
  header_left(ed) +
  header_top(stat) +
  header_top_left(genotype) +
  header_format(stat, 
                style = list(cell_text(align = "center"),
                             cell_borders(sides = c("bottom", "top"), 
                                          color = "lightgrey",
                                          weight = px(2))))

print(ed_table)

ed_table %>% gtsave("EmT_table.png")
```

```{r}
ed_tableplot <- png::readPNG("EmT_table.png", native = TRUE)
```

```{r cumulative plot}
p_cumulative <- relative_cummulative %>%
  dplyr::mutate(day = as.numeric(as.character(day))) %>% 
  dplyr::filter(stage == "fourth") %>% 
  dplyr::filter(day > 9) %>% 
  dplyr::group_by(genotype) %>% 
  ggplot() +
  theme_simple() +
  labs(y = "development to 4th instar (%)",
       x = "days after infection") +
  scale_color_manual(values = palette) +
  scale_fill_manual(values = palette) +
  geom_crossbar(aes(x = day,
                y = median_abundance,
                ymin = ymin_ribbon,
                ymax = ymax_ribbon,
                fill = genotype,
                color = genotype),
                alpha = 0.3,
                width = 0.5) +
  geom_errorbar(aes(x = day,
                  ymin = ymax_ribbon,
                  ymax = max_whisker,
                  color = genotype),
                width = 0,
                size = 0.5) +
  geom_errorbar(aes(x = day,
                  ymin = min_whisker,
                  ymax = ymin_ribbon,
                  color = genotype),
                width = 0,
                size = 0.5) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 100)) +
  xlim(13,NA)

p_cumulative <- p_cumulative +
  stat_smooth(data = ED %>%
  dplyr::group_by(id) %>% 
  dplyr::mutate(day = as.numeric(as.character(day))),
              aes(x=day, y=number, color = genotype),
              method = drm, 
              method.args = list(fct = LL.3()), 
              se = FALSE) 
```


### area under the curve

```{r auc, fig.width = 16, fig.height = 20}
library(DescTools)

auc_fourth <- auc %>%
  dplyr::filter(stage == "fourth") %>% 
  dplyr::mutate(day = as.numeric(as.character(day)))  %>%
  dplyr::mutate(number = number/100)  %>%
  dplyr::ungroup()

  rel_cumul = tibble()
  for(i in c("LA1840_1", "MM_2", "MM_3", "LA1840_5", "LA1840_6", "LA1840_7", "MM_8", "MM_9", "MM_10", "LA1840_11", "LA1840_12")){
    subdata = subset(auc_fourth, id == i)
    subdata[[i]] = AUC(subdata$day, subdata$number)
    rel_cumul <- bind_rows(rel_cumul, subdata)
  }

  auc_fourth <- rel_cumul %>%
    unite("auc", LA1840_1:LA1840_12, 
          na.rm = TRUE) %>%  
  dplyr::filter(day == 2) %>% 
    dplyr::mutate(auc = as.numeric(as.character(auc)))

  
auc_plot <- auc_fourth %>% 
    ggplot(aes(x=genotype, y=auc, fill=genotype)) + 
    labs(y = "area under the curve",
         x= "rootstock genotype") +
    geom_boxplot() + 
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 0.4)) +
    theme_simple() + 
    scale_fill_manual(values = palette) +
  stat_compare_means(method = "t.test", 
                     label.y = 9.2,
                     label.x = 1.5,
                     size = 5,
                     label = "p.format") + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 10)) 

p_line <- p_cumulative + inset_element(auc_plot, 
                             left = 0.65, 
                             bottom = 0.025, 
                             right = 1, 
                             top = 0.55)

layout <- "
  AABBCC
  AABBCC
  DDDD##
  DDDDEE
  DDDDEE
"
layout2 <- "
  AAABBBCCC
  AAABBBCCC
  DDDDDDEEE
  DDDDDDEEE
  DDDDDDFFF
  GGGGGGGGG
"

development_plot <- ((p_eggs | p_first | p1) / (((p_cumulative + inset_element(auc_plot, 
                             left = 0.65, 
                             bottom = 0.025, 
                             right = 1, 
                             top = 0.55))) | ed_tableplot)) + guide_area() +
  plot_layout(guides = 'collect',
              design = layout) +
  plot_annotation(tag_levels = 'A')

development_plot1 <- (p_eggs + p_first + p1 + p_line + ed_tableplot) + guide_area() +
  plot_layout(guides = 'collect',
              design = layout) +
  plot_annotation(tag_levels = 'A')

development_plot2 <- (p_eggs + p_first + p1 + p_cumulative + auc_plot + ed_tableplot) + guide_area() +
  plot_layout(guides = 'collect',
              design = layout2) +
  plot_annotation(tag_levels = 'A')

development_plot2

ggsave(filename = "graft_bioassay.svg", plot = development_plot2, width = 10, height = 12)

ggsave(filename = "graft_bioassay.png", plot = development_plot2, width = 10, height = 12)
```

```{r relative cumulative graph, fig.width = 16, fig.height = 10}
p_cumulative <- relative_cummulative %>%
  dplyr::mutate(stage = factor(stage, 
                        levels = c("first", "second", "third", "fourth"))) %>%
  dplyr::mutate(day = as.numeric(as.character(day))) %>% 
  dplyr::filter(stage == "fourth") %>% 
  dplyr::filter(day > 9) %>% 
  dplyr::group_by(genotype) %>% 
  ggplot() +
  theme_simple() +
  labs(y = "development to 4th instar (%)",
       x = "days after infection") +
  scale_color_manual(values = palette) +
  scale_fill_manual(values = palette) +
#  geom_line(aes(x = day,
#                  y = min_abundance,
#                  color = genotype),
#              linetype = "dotted") +
#  geom_line(aes(x = day,
#                  y = max_abundance,
#                  color = genotype),
#              linetype = "dotted") +
  geom_ribbon(aes(x = day,
                  ymin = ymin_ribbon,
                  ymax = (median_abundance + (0.5*IQR_abundance)),
                  fill = genotype),
              alpha = 0.35) +
  geom_line(aes(x = day,
                y = median_abundance,
                color = genotype),
            size = 1) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 100)) +
  xlim(13,NA)
#  facet_rep_wrap(vars(stage), nrow = 1) +
#  scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
#  theme(panel.spacing = unit(0.1, "lines"))

p_cumulative 

#ggsave(filename = "graft_bioassay_lineplots_4th.png", plot = p_cumulative, width = 10, height = 5)
```



## relative abundance

```{r new df}
relative_abundance <- flies %>%
  dplyr::select(-eggs_start: -`0_egg`,
                -`4_early_fourth_instar`:-`5_completed_lifecycle`)
```

```{r total abundance}
relative_abundance <- relative_abundance %>%
  rowwise() %>%
  mutate(total = sum(c_across(`1_first_instar`:`6_total_fourth_instars`),
                     na.rm = TRUE))
  
```

```{r relative abundances}
relative_abundance <- relative_abundance %>%
  mutate(first = `1_first_instar`/total) %>%
  mutate(second = `2_second_instar`/total) %>%
  mutate(third = `3_third_instar`/total) %>%
  mutate(fourth = `6_total_fourth_instars`/total)
```

```{r clean df}
relative_abundance <- relative_abundance %>%
  dplyr::select(-`1_first_instar`: -`6_total_fourth_instars`) %>%
  subset(total>0)
```

```{r longer}
relative_abundance <- relative_abundance %>%
  dplyr::select(-total) %>%
  pivot_longer(cols = first:fourth, 
               names_to = "stage", values_to = "relat_abund") %>%
  mutate(genotype = factor(genotype, levels = c("MM", "LA1840")))

# 10 rows of middle of the data
#knitr::kable(relative_abundance[41:51,1:6])
```

```{r wide3}
relative_abundance <- relative_abundance %>%
  mutate(stage = as.factor(stage)) %>%
  mutate(place = as.factor(place)) %>%
  group_by(stage, genotype) %>%
  pivot_wider(names_from = place, values_from = relat_abund) 

``` 

```{r summarised}
relative_abundance <- relative_abundance %>%
  mutate(day = as.factor(day)) %>%
  rowwise() %>%
  mutate(median_abundance = median(c_across(`1`:`12`), na.rm = TRUE)) %>%
  mutate(sd_abundance = sd(c_across(`1`:`12`), na.rm = TRUE)) %>%
  mutate(max_abundance = max(c_across(`1`:`12`), na.rm = TRUE)) %>%
  mutate(min_abundance = min(c_across(`1`:`12`), na.rm = TRUE)) %>%
  mutate(ymin_ribbon = (median_abundance - sd_abundance)) %>%
  mutate(ymin_ribbon = if_else(ymin_ribbon < 0, 0, ymin_ribbon))

relative_abundance <- relative_abundance %>%
  dplyr::select(-`1`: -`12`) 

# 10 rows of middle of the data
knitr::kable(relative_abundance[41:51,1:9])
```

```{r relative abundance on MM, eval=FALSE, include=FALSE}
MMpalette <- c("#E69F00")
#MMpalette <- c("#FF8900", "#FFB300", "#FFCD00", "#FFE280")
pMM <- relative_abundance %>%
  mutate(stage = factor(stage, 
                        levels = c("first", "second", "third", "fourth"))) %>%
  dplyr::filter(genotype == "MM") %>% 
  mutate(day = as.numeric(as.character(day))) %>% 
  group_by(stage) %>% 
  ggplot() +
  theme_simple() +
  labs(y = "relative abundance",
       x = "days after infection") +
  scale_color_manual(values = MMpalette) +
  scale_fill_manual(values = MMpalette) +
  geom_line(aes(x = day,
                  y = min_abundance,
                  color = genotype),
              linetype = "dotted") +
  geom_line(aes(x = day,
                  y = max_abundance,
                  color = genotype),
              linetype = "dotted") +
  geom_ribbon(aes(x = day,
                  ymin = ymin_ribbon,
                  ymax = (median_abundance + sd_abundance),
                  fill = genotype),
              alpha = 0.35) +
  geom_line(aes(x = day,
                y = median_abundance,
                color = genotype),
            size = 1.2) +
  facet_wrap(vars(stage), nrow = 4) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA))
```


```{r relative abundance graph, fig.width = 8, fig.height = 15}
#LApalette <- c("#0062F6", "#008DFF", "#2CB9FF", "#91E6FF")
p_abundance <- relative_abundance %>%
  mutate(stage = factor(stage, 
                        levels = c("first", "second", "third", "fourth"))) %>%
  #dplyr::filter(genotype == "LA1840") %>% 
  mutate(day = as.numeric(as.character(day))) %>% 
  group_by(genotype) %>% 
  ggplot() +
  theme_simple() +
  labs(y = "relative abundance per plant",
       x = "days after infection") +
  scale_color_manual(values = palette) +
  scale_fill_manual(values = palette) +
  geom_line(aes(x = day,
                  y = min_abundance,
                  color = genotype),
              linetype = "dotted") +
  geom_line(aes(x = day,
                  y = max_abundance,
                  color = genotype),
              linetype = "dotted") +
  geom_ribbon(aes(x = day,
                  ymin = ymin_ribbon,
                  ymax = (median_abundance + sd_abundance),
                  fill = genotype),
              alpha = 0.35) +
  geom_line(aes(x = day,
                y = median_abundance,
                color = genotype),
            size = 1) +
  facet_rep_wrap(vars(stage), nrow = 1) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
  theme(panel.spacing = unit(0.1, "lines"))


(p_abundance / p_cumulative) / guide_area() +
  plot_layout(guides = 'collect') 
              heights = unit(c(30, 30), 'cm'))
```
```

