---
title: "IL bioassay"
author: "Lissy Denkers"
date: "`r Sys.Date()`"
output: 
  pdf_document: default
  html_document: default
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.width = 8, 
                      fig.height = 5, 
                      fig.align = "center")
suppressPackageStartupMessages(library("ggplot2"))
suppressPackageStartupMessages(library("ggpubr"))
suppressPackageStartupMessages(library("ggpubfigs"))
suppressPackageStartupMessages(library("patchwork"))
suppressPackageStartupMessages(library("multcomp"))
suppressPackageStartupMessages(library("car"))
suppressPackageStartupMessages(library("tidyverse"))
suppressPackageStartupMessages(library("rstatix"))
suppressPackageStartupMessages(library("broom"))
```

# Data import 

## Background information

This is the  the whitefly development bioassay on the ILs performed by Arjen van Doorn. Only the cultivated parent (MB) is included, not LA1840. IL29 will be excluded from the data, because it is not part of the metabolomics data.

## The raw data
```{r flies}
flies <- read.csv("IL_screen.csv", 
                         header = T, 
                         sep = ",", 
                         dec = ".", 
                         check.names = FALSE)%>%     
  dplyr::filter(genotype != "IL29") %>%
  mutate_if(is.character, str_replace_all, 
            pattern = "KG1955", replacement = "MB") %>%
  mutate_if(is.character, str_replace_all, 
            pattern = "eggs", replacement = "egg") %>%
  mutate(genotype = factor(genotype, levels = c("MB", "IL28", "IL27"))) %>%
  mutate(stage = factor(stage, levels = c("egg", "fourth_instar")))
# The first 10 rows of the data
knitr::kable(flies[1:10,1:4])
```

# plots
```{r absolute plot}
palette <- c("#E69F00", "#D55E00", "#0072B2")
```

```{r combined plot}
p1 <- flies %>% 
  dplyr::filter(stage == "egg") %>%
  ggplot(aes(x=genotype, y=number, fill=genotype)) + 
  labs(y = "eggs (count)") +
  ylim(0,130) +
  geom_boxplot() + 
  theme_simple() + 
  scale_fill_manual(values = palette) 

p2 <- flies %>% 
  dplyr::filter(stage == "fourth_instar") %>%
  ggplot(aes(x=genotype, y=number, fill=genotype)) + 
  labs(y = "4th instar nymphs (count)") +
  geom_boxplot() + 
  theme_simple() + 
  scale_fill_manual(values = palette) 

p3 <- flies %>% 
  pivot_wider(names_from = stage, values_from = number) %>%
  mutate(percentage_from_eggs = fourth_instar / egg * 100) %>%
  pivot_longer(cols = fourth_instar:percentage_from_eggs, 
               names_to = "stage", values_to = "number") %>%
  dplyr::filter(stage == "percentage_from_eggs") %>%
  ggplot(aes(x=genotype, y=number, fill=genotype)) + 
  labs(y = "development to 4th instar (%)") +
  geom_boxplot() + 
  theme_simple() + 
  scale_fill_manual(values = palette) 

(p1 + p2 + p3) / guide_area() +
  plot_layout(guides = 'collect')
```


# statistics
Are the number of 4th instars lower than the number of eggs per genotype?
```{r paired t-test}
flies %>%
  group_by(genotype) %>%
  pairwise_t_test(
    number ~ stage, paired = TRUE, 
    p.adjust.method = "bonferroni"
  )
```

