---
title: "leaf dips results"
author: "Lissy Denkers"
date: "2024-02-05"
output: html_document
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.width = 20, 
                      fig.height = 32, 
                      fig.align = "center")
suppressPackageStartupMessages(library("ggplot2"))
suppressPackageStartupMessages(library("ggpubr"))
suppressPackageStartupMessages(library("ggpubfigs"))
suppressPackageStartupMessages(library("ggsignif"))
suppressPackageStartupMessages(library("patchwork"))
suppressPackageStartupMessages(library("multcomp"))
suppressPackageStartupMessages(library("car"))
suppressPackageStartupMessages(library("tidyverse"))
suppressPackageStartupMessages(library("rstatix"))
suppressPackageStartupMessages(library("broom"))
suppressPackageStartupMessages(library("DescTools"))
```

## Leaf dips

Results of GC-MS on leaf dips of MM, MB and 4 *S. chmielewskii's*


```{r loading data}
dataset <- read.csv("./20240125_results_GCMS.csv", 
                         header = T, 
                         sep = ",", 
                         dec = ".", 
                         check.names = FALSE) 
```


```{r average technical replicates}
terpenes <- dataset %>%
  dplyr::select(-sample_id) %>%
  pivot_longer(cols = alpha_pinene : neridol, 
               names_to = "compound", values_to = "value")  %>%
  pivot_wider(names_from = tec_replicate, values_from = value, names_prefix = "tec_rep_") %>%
  dplyr::mutate(concentration = rowMeans(select(terpenes, 
                                              tec_rep_1:tec_rep_2), na.rm = TRUE)) %>%
  dplyr::select(-tec_rep_1:-tec_rep_2)
```

```{r wide and order}
  terpenes <- terpenes %>%
  pivot_wider(names_from = compound, values_from = concentration) %>%
  mutate(genotype = factor(genotype, levels = c("MM", "MB", "LA1028", "LA1330", "LA1840", "LA2663")))

```


```{r create palette}
palette <- c("#E69F00", "#E69F00", "#bbe1f6", "#88caef", "#56B4E9", "#4490ba")
```

```{r check color palette}
library(colorblindcheck)
palette_check(palette, plot=TRUE)
```

```{r making plots, fig.width = 8, fig.height = 20}
pinene <- terpenes %>% 
  ggplot(aes(x=genotype, y=alpha_pinene)) + 
  labs(y = "alpha-pinene") +
  geom_boxplot(aes(fill = genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 1.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))  
  #scale_y_continuous(expand = c(0, 0), limits = c(0, 18000))  
  
a_phellandrene <- terpenes %>% 
  ggplot(aes(x=genotype, y=alpha_phellandrene)) + 
  labs(y = "alpha-phellandrene") +
  geom_boxplot(aes(fill = genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 1.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))  
  #scale_y_continuous(expand = c(0, 0), limits = c(0, 18000))  
  
terpinene <- terpenes %>% 
  ggplot(aes(x=genotype, y=alpha_terpinene)) + 
  labs(y = "alpha-terpinene") +
  geom_boxplot(aes(fill = genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 1.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))   
  #scale_y_continuous(expand = c(0, 0), limits = c(0, 18000))  
  
limonene <- terpenes %>% 
  ggplot(aes(x=genotype, y=d_limonene)) + 
  labs(y = "D-limonene") +
  geom_boxplot(aes(fill = genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 0.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))   
  #scale_y_continuous(expand = c(0, 0), limits = c(0, 18000))  
  
b_phellandrene <- terpenes %>% 
  ggplot(aes(x=genotype, y=b_phellandrene)) + 
  labs(y = "beta-phellandrene") +
  geom_boxplot(aes(fill = genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 1.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))   
  #scale_y_continuous(expand = c(0, 0), limits = c(0, 18000)) 
  
ocimene <- terpenes %>% 
  ggplot(aes(x=genotype, y=trans_b_ocimene)) + 
  labs(y = "trans-beta-ocimene") +
  geom_boxplot(aes(fill = genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 1.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))   
  #scale_y_continuous(expand = c(0, 0), limits = c(0, 18000))  
  
linalool <- terpenes %>% 
  ggplot(aes(x=genotype, y=linalool)) + 
  labs(y = "linalool") +
  geom_boxplot(aes(fill = genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 1.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))   
  #scale_y_continuous(expand = c(0, 0), limits = c(0, 18000)) 
  
terpinolene <- terpenes %>% 
  ggplot(aes(x=genotype, y=terpinolene)) + 
  labs(y = "terpinolene") +
  geom_boxplot(aes(fill = genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 1.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))   
  #scale_y_continuous(expand = c(0, 0), limits = c(0, 18000)) 
  
geraniol <- terpenes %>% 
  ggplot(aes(x=genotype, y=geraniol)) + 
  labs(y = "geraniol") +
  geom_boxplot(aes(fill = genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 1.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))   
  #scale_y_continuous(expand = c(0, 0), limits = c(0, 18000)) 
  
caryophyllene <- terpenes %>% 
  ggplot(aes(x=genotype, y=beta_caryophyllene)) + 
  labs(y = "beta-caryophyllene") +
  geom_boxplot(aes(fill = genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 1.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))   
  #scale_y_continuous(expand = c(0, 0), limits = c(0, 18000)) 
  
humulene <- terpenes %>% 
  ggplot(aes(x=genotype, y=alpha_humulene)) + 
  labs(y = "alpha-humulene") +
  geom_boxplot(aes(fill = genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 1.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))   
  #scale_y_continuous(expand = c(0, 0), limits = c(0, 18000)) 
  
cuparene <- terpenes %>% 
  ggplot(aes(x=genotype, y=cuparene)) + 
  labs(y = "cuparene") +
  geom_boxplot(aes(fill = genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 1.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))   
  #scale_y_continuous(expand = c(0, 0), limits = c(0, 18000)) 
  
neridol <- terpenes %>% 
  ggplot(aes(x=genotype, y=neridol)) + 
  labs(y = "neridol") +
  geom_boxplot(aes(fill = genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 1.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))   
  #scale_y_continuous(expand = c(0, 0), limits = c(0, 18000)) 


collected <- (pinene + a_phellandrene + terpinene + limonene + b_phellandrene + ocimene + linalool + terpinolene + geraniol + caryophyllene + humulene + cuparene + neridol) / guide_area() +
  plot_layout(guides = 'collect') +
  plot_annotation(tag_levels = '1')

collected
```

```{r save plot}
ggsave(filename = "terpene_boxplots.png", plot = collected, width = 15, height = 25)
```


## Leaf dips normalised

Results of GC-MS on leaf dips of MM, MB and 4 *S. chmielewskii's*, normalised to leaf weight


```{r loading data}
normalised_dataset <- read.csv("./20240125_results_GCMS_normalised.csv", 
                         header = T, 
                         sep = ",", 
                         dec = ".", 
                         check.names = FALSE) 
```


```{r average technical replicates}
normalised_terpenes <- normalised_dataset %>%
  dplyr::select(-sample_id) %>%
  pivot_longer(cols = alpha_pinene : neridol, 
               names_to = "compound", values_to = "value")  %>%
  pivot_wider(names_from = tec_replicate, values_from = value, names_prefix = "tec_rep_") 

normalised_terpenes <- normalised_terpenes %>%
  dplyr::mutate(concentration = rowMeans(subset(normalised_terpenes, select = c(tec_rep_1, tec_rep_2)), na.rm = TRUE)) %>%
  dplyr::select(-tec_rep_1:-tec_rep_2)

```

```{r wide and order}
normalised_terpenes <- normalised_terpenes %>%
  pivot_wider(names_from = compound, values_from = concentration) %>%
  mutate(genotype = factor(genotype, levels = c("MM", "MB", "LA1028", "LA1330", "LA1840", "LA2663")))

```


```{r create palette}
palette <- c("#E69F00", "#E69F00", "#bbe1f6", "#88caef", "#56B4E9", "#4490ba")
```

```{r check color palette}
library(colorblindcheck)
palette_check(palette, plot=TRUE)
```

```{r making plots, fig.width = 8, fig.height = 20}
pinene <- normalised_terpenes %>% 
  ggplot(aes(x=genotype, y=alpha_pinene)) + 
  labs(y = "alpha-pinene") +
  geom_boxplot(aes(fill = genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 1.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  stat_compare_means(method = "anova", label.x.npc = "centre", label.y = 0.5, label = "p.format", size = 5) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 0.55))  
  
a_phellandrene <- normalised_terpenes %>% 
  ggplot(aes(x=genotype, y=alpha_phellandrene)) + 
  labs(y = "alpha-phellandrene") +
  geom_boxplot(aes(fill = genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 1.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  stat_compare_means(method = "anova", label.x.npc = "centre", label.y = 0.82, label = "p.format", size = 5) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 0.9))  
  
terpinene <- normalised_terpenes %>% 
  ggplot(aes(x=genotype, y=alpha_terpinene)) + 
  labs(y = "alpha-terpinene") +
  geom_boxplot(aes(fill = genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 1.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  stat_compare_means(method = "anova", label.x.npc = "centre", label.y = 1.27, label = "p.format", size = 5) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1.4))    
  
limonene <- normalised_terpenes %>% 
  ggplot(aes(x=genotype, y=d_limonene)) + 
  labs(y = "D-limonene") +
  geom_boxplot(aes(fill = genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 1.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  stat_compare_means(method = "anova", label.x.npc = "centre", label.y = 3.64, label = "p.format", size = 5) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 4))  
  
b_phellandrene <- normalised_terpenes %>% 
  ggplot(aes(x=genotype, y=b_phellandrene)) + 
  labs(y = "beta-phellandrene") +
  geom_boxplot(aes(fill = genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 1.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  stat_compare_means(method = "anova", label.x.npc = "centre", label.y = 3.64, label = "p.format", size = 5) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 4))  
  
ocimene <- normalised_terpenes %>% 
  ggplot(aes(x=genotype, y=trans_b_ocimene)) + 
  labs(y = "trans-beta-ocimene") +
  geom_boxplot(aes(fill = genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 1.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  stat_compare_means(method = "anova", label.x.npc = "centre", label.y = 0.364, label = "p.format", size = 5) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 0.4))  
  
linalool <- normalised_terpenes %>% 
  ggplot(aes(x=genotype, y=linalool)) + 
  labs(y = "linalool") +
  geom_boxplot(aes(fill = genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 1.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  stat_compare_means(method = "anova", label.x.npc = "centre", label.y = 0.118, label = "p.format", size = 5) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 0.13))  
  
terpinolene <- normalised_terpenes %>% 
  ggplot(aes(x=genotype, y=terpinolene)) + 
  labs(y = "terpinolene") +
  geom_boxplot(aes(fill = genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 1.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  stat_compare_means(method = "anova", label.x.npc = "centre", label.y = 0.0636, label = "p.format", size = 5) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 0.07))  
  
geraniol <- normalised_terpenes %>% 
  ggplot(aes(x=genotype, y=geraniol)) + 
  labs(y = "geraniol") +
  geom_boxplot(aes(fill = genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 1.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  stat_compare_means(method = "anova", label.x.npc = "centre", label.y = 1.45, label = "p.format", size = 5) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1.6))  
  
caryophyllene <- normalised_terpenes %>% 
  ggplot(aes(x=genotype, y=beta_caryophyllene)) + 
  labs(y = "beta-caryophyllene") +
  geom_boxplot(aes(fill = genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 1.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  stat_compare_means(method = "anova", label.x.npc = "centre", label.y = 0.727, label = "p.format", size = 5) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 0.8))  
  
humulene <- normalised_terpenes %>% 
  ggplot(aes(x=genotype, y=alpha_humulene)) + 
  labs(y = "alpha-humulene") +
  geom_boxplot(aes(fill = genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 1.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  stat_compare_means(method = "anova", label.x.npc = "centre", label.y = 4.09, label = "p.format", size = 5) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 4.5))  
  
cuparene <- normalised_terpenes %>% 
  ggplot(aes(x=genotype, y=cuparene)) + 
  labs(y = "cuparene") +
  geom_boxplot(aes(fill = genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 1.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  stat_compare_means(method = "anova", label.x.npc = "centre", label.y = 0.182, label = "p.format", size = 5) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 0.2))  
  
neridol <- normalised_terpenes %>% 
  ggplot(aes(x=genotype, y=neridol)) + 
  labs(y = "neridol") +
  geom_boxplot(aes(fill = genotype)) +   
  geom_point(aes(fill = genotype), size = 2, shape = 21,
             position = position_jitterdodge(jitter.width = 1.4)) + 
  theme_simple() + 
  scale_fill_manual(values = palette) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  stat_compare_means(method = "anova", label.x.npc = "centre", label.y = 8.18, label = "p.format", size = 5) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 9))   


collected <- (pinene + a_phellandrene + terpinene + limonene + b_phellandrene + ocimene + linalool + terpinolene + geraniol + caryophyllene + humulene + cuparene + neridol + plot_layout(ncol = 3)) / guide_area() +
  plot_layout(guides = 'collect') +
  plot_annotation(tag_levels = 'a')

collected
```

```{r save plot}
ggsave(filename = "terpene_boxplots_normalised.png", plot = collected, width = 10, height = 30)
```
